-- Run in Supabase SQL Editor after migrations (including cable_sheet_tables).
-- Idempotent-ish: remove or adjust if you already seeded these ranges/products.

-- Daily dispatch capacity (keys match getLatestDispatchLimitRange in src/lib/db.js)
INSERT INTO public.daily_capacity (sort_order, record)
VALUES (
  0,
  $${
    "Start Date": "2025-06-03",
    "End Date": "2025-06-30",
    "Limit": 10000
  }$$::jsonb
);

INSERT INTO public.cable_products (sort_order, record) VALUES
(0, $${
  "productCode": "20010069",
  "productName": "COMPRESSSSOR WIRE HARNESS",
  "productFamily": "Power Cords",
  "cableType": "Three Core",
  "strandCount": "24",
  "conductorMaterial": "Copper",
  "conductorSize": "1.5",
  "conductorConstruction": "",
  "insulationMaterial": "",
  "insulationThickness": "",
  "jacketMaterial": "",
  "jacketThickness": "",
  "shieldType": "",
  "armorType": "",
  "coreCount": "3",
  "coreColors": "[\"Red\",\"Black\",\"Yellow-Green\"]",
  "cableProfile": "",
  "outerDiameter": "",
  "standardLength": "1.8",
  "minLength": "",
  "maxLength": "",
  "temperatureRating": "",
  "flameRating": "",
  "complianceStandards": "",
  "ipRating": "",
  "bendRadius": "",
  "weightPerMeter": "",
  "applicationArea": "",
  "isActive": "true",
  "specifications": "",
  "remarks": "",
  "createdDate": "2025-10-01",
  "lastModified": ""
}$$::jsonb),
(1, $${
  "productCode": "PVC-6A-3C-1.5MM-1.8M",
  "productName": "PVC 3-Core Power Cord 6A 1.8M",
  "productFamily": "Power Cords",
  "cableType": "three_core",
  "strandCount": "24",
  "conductorMaterial": "Copper",
  "conductorSize": "1.5",
  "conductorConstruction": "24/0.20mm",
  "insulationMaterial": "PVC",
  "insulationThickness": "0.7",
  "jacketMaterial": "PVC",
  "jacketThickness": "1.2",
  "shieldType": "None",
  "armorType": "None",
  "coreCount": "3",
  "coreColors": "[\"Brown\", \"Blue\", \"Yellow-Green\"]",
  "cableProfile": "Round",
  "outerDiameter": "8.5",
  "standardLength": "1.8",
  "minLength": "0.5",
  "maxLength": "15",
  "temperatureRating": "70°C",
  "flameRating": "VW-1",
  "complianceStandards": "IEC 60227, IS 694",
  "ipRating": "IP20",
  "bendRadius": "42.5",
  "weightPerMeter": "95",
  "applicationArea": "Domestic Appliances",
  "isActive": "TRUE",
  "specifications": "Standard 6A power cord for household appliances",
  "remarks": "Most common power cord product",
  "createdDate": "2025-09-06",
  "lastModified": "2025-09-06"
}$$::jsonb),
(2, $${
  "productCode": "XLPE-16A-3C-2.5MM-3M",
  "productName": "XLPE 3-Core Industrial Cable 16A 3M",
  "productFamily": "Industrial Cables",
  "cableType": "three_core",
  "strandCount": "50",
  "conductorMaterial": "Copper",
  "conductorSize": "2.5",
  "conductorConstruction": "50/0.25mm",
  "insulationMaterial": "XLPE",
  "insulationThickness": "0.9",
  "jacketMaterial": "PVC",
  "jacketThickness": "1.8",
  "shieldType": "Braided",
  "armorType": "None",
  "coreCount": "3",
  "coreColors": "[\"Brown\", \"Blue\", \"Yellow-Green\"]",
  "cableProfile": "Round",
  "outerDiameter": "12.8",
  "standardLength": "3",
  "minLength": "1",
  "maxLength": "50",
  "temperatureRating": "90°C",
  "flameRating": "IEC 60332-1",
  "complianceStandards": "IEC 60245, CE",
  "ipRating": "IP44",
  "bendRadius": "64",
  "weightPerMeter": "185",
  "applicationArea": "Industrial Equipment",
  "isActive": "TRUE",
  "specifications": "Heavy-duty industrial cable with XLPE insulation",
  "remarks": "For harsh industrial environments",
  "createdDate": "2025-09-06",
  "lastModified": "2025-09-06"
}$$::jsonb);

-- Cable production plans: created from Cable Production Planning UI (batchInfo, materialRequirements, etc.).
