-- Run after public.cable_production_plans exists (see cable_sheet_tables migration).
-- Includes `length` for CableProductionPlanning table UI (shows plan.length + "m").

INSERT INTO public.cable_production_plans (sort_order, record) VALUES
(0, $${
  "planId": "PDP-1760705436723",
  "orderNumber": "SO-12345",
  "customerName": "C10044",
  "productCode": "INDUCTION 3 C 3 PIN MAIN LEAD",
  "productName": "",
  "quantity": "4000",
  "length": "",
  "requiredLength": "",
  "totalMeters": "",
  "dueDate": "2025-10-17T12:45:32.773Z",
  "priority": "Medium",
  "status": "Planning",
  "productionMethod": "",
  "qualityRequirements": "",
  "specialInstructions": "",
  "materialAllocated": "",
  "machineAllocated": "",
  "estimatedStartDate": "",
  "estimatedCompletionDate": "",
  "actualStartDate": "",
  "actualCompletionDate": "",
  "completedQuantity": "",
  "rejectedQuantity": "",
  "materialWastage": "",
  "efficiency": "",
  "remarks": "",
  "createdBy": "",
  "createdDate": "2025-10-17T12:45:32.773Z",
  "lastModified": "",
  "coreColors": "[]",
  "numberOfCores": "",
  "materialRequirements": "{}",
  "machineSchedule": "{}",
  "batchInfo": ""
}$$::jsonb),
(1, $${
  "planId": "PDP-1761326110230",
  "orderNumber": "SO-123456",
  "customerName": "C10044",
  "productCode": "Power cord",
  "productName": "",
  "quantity": "2000",
  "length": "",
  "requiredLength": "",
  "totalMeters": "",
  "dueDate": "2025-10-24T17:14:58.921Z",
  "priority": "Medium",
  "status": "Planning",
  "productionMethod": "",
  "qualityRequirements": "",
  "specialInstructions": "",
  "materialAllocated": "",
  "machineAllocated": "",
  "estimatedStartDate": "",
  "estimatedCompletionDate": "",
  "actualStartDate": "",
  "actualCompletionDate": "",
  "completedQuantity": "",
  "rejectedQuantity": "",
  "materialWastage": "",
  "efficiency": "",
  "remarks": "",
  "createdBy": "",
  "createdDate": "2025-10-24T17:14:58.921Z",
  "lastModified": "",
  "coreColors": "[]",
  "numberOfCores": "",
  "materialRequirements": "{}",
  "machineSchedule": "{}",
  "batchInfo": ""
}$$::jsonb);
